# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubyhaze}
  s.version = "0.0.6"
  s.platform = %q{jruby}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Madrid"]
  s.date = %q{2010-09-08}
  s.default_executable = %q{rubyhaze_console}
  s.description = %q{RubyHaze is a little gem that wraps the Java Hazelcast library into a more comfortable JRuby package.}
  s.email = %q{aemadrid@gmail.com}
  s.executables = ["rubyhaze_console"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/rubyhaze_console",
     "jars/hazelcast-1.9-RC.jar",
     "jars/hazelcast-client-1.9-RC.jar",
     "lib/rubyhaze.rb",
     "lib/rubyhaze/client.rb",
     "lib/rubyhaze/configs/config.rb",
     "lib/rubyhaze/configs/group.rb",
     "lib/rubyhaze/configs/map.rb",
     "lib/rubyhaze/configs/network.rb",
     "lib/rubyhaze/configs/queue.rb",
     "lib/rubyhaze/configs/topic.rb",
     "lib/rubyhaze/list.rb",
     "lib/rubyhaze/lock.rb",
     "lib/rubyhaze/map.rb",
     "lib/rubyhaze/mixins/compare.rb",
     "lib/rubyhaze/mixins/do_proxy.rb",
     "lib/rubyhaze/mixins/native_exception.rb",
     "lib/rubyhaze/mixins/proxy.rb",
     "lib/rubyhaze/multi_map.rb",
     "lib/rubyhaze/node.rb",
     "lib/rubyhaze/queue.rb",
     "lib/rubyhaze/set.rb",
     "lib/rubyhaze/topic.rb",
     "test/helper.rb",
     "test/test_hash.rb",
     "test/test_queue.rb",
     "test/test_topic.rb"
  ]
  s.homepage = %q{http://github.com/aemadrid/rubyhaze}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Hazelcast distributed objects in my JRuby}
  s.test_files = [
    "test/test_hash.rb",
     "test/test_queue.rb",
     "test/test_topic.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

